rental:
  house:
    asset:
      service:
        name: asset-service
        base:
          uri: http://${rental.house.asset.service.name}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo}/asset-rental-deal-service
  application:
    name: asset-rental-deal-service
  cloud:
    stream:
      bindings:
        rentalDeals:
          destination: rentalDeals
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
  instance:
    preferIpAddress: true